defmodule Surfex.GoldenTest do
  @moduledoc """
  The renderer's two load-bearing claims, and its notation.

  **Order-invariance** is the property every drift gate rests on: a scanner that returned
  rows in a different order on a different run would fail the gate with no change to the
  code, and a gate that fails for no reason is a gate somebody switches off.

  **No dates** is the same failure by another route — a golden carrying a timestamp drifts
  against itself on a quiet day. It is asserted here rather than remembered, because it is
  the rule most likely to be re-broken by someone adding a helpful "generated at".
  """

  use ExUnit.Case, async: true

  alias Surfex.Golden

  defp spec(overrides \\ %{}) do
    Map.merge(
      %{
        name: "EXAMPLE_SURFACE.md",
        purpose: "Every widget the code declares, and what verifies it.",
        task: "example.surface",
        gate: "example-surface-drift",
        hardness: :hard,
        columns: ["Item", "Evidence", "Locus"],
        rows: [
          %{
            "Item" => {:code, "alpha"},
            "Evidence" => {:atom, :unit_test},
            "Locus" => {:locus, "lib/a.ex", nil}
          },
          %{"Item" => {:code, "beta"}, "Evidence" => :absent, "Locus" => {:locus, "lib/b.ex", 12}}
        ]
      },
      overrides
    )
  end

  describe "the header block" do
    test "is title, purpose, attribution — in that order, contiguous" do
      [title, purpose, attribution | _] = Golden.render(spec()) |> String.split("\n")

      assert title == "# EXAMPLE_SURFACE.md"
      assert purpose == "Every widget the code declares, and what verifies it."
      assert attribution =~ "Generated by `mix example.surface --write`"
      assert attribution =~ "gate `example-surface-drift`"
      assert attribution =~ "(HARD)"
      assert attribution =~ "do not edit; a drift FAILS the gate"
    end

    test "says ADVISORY when the gate is advisory, so the document states its own force" do
      rendered = Golden.render(spec(%{hardness: :advisory}))

      assert rendered =~ "(ADVISORY)"
      refute rendered =~ "(HARD)"
    end
  end

  describe "determinism" do
    # The property the drift gates rest on. Two scanners that agree on content but not on
    # order must produce identical bytes.
    test "row order does not change the bytes" do
      forward = spec()
      reversed = %{forward | rows: Enum.reverse(forward.rows)}

      assert Golden.render(reversed) == Golden.render(forward)
    end

    test "nor does the order of a row map's keys" do
      forward = spec()

      shuffled = %{
        forward
        | rows: Enum.map(forward.rows, &Map.new(Enum.shuffle(Map.to_list(&1))))
      }

      assert Golden.render(shuffled) == Golden.render(forward)
    end

    test "and rendering twice is rendering once" do
      assert Golden.render(spec()) == Golden.render(spec())
    end
  end

  describe "what may never appear" do
    # A golden is a stable function of source. Anything that varies independently of source
    # makes it drift against itself, and a gate that cries wolf gets disabled.
    test "no date, time or duration reaches the output" do
      rendered = Golden.render(spec())

      refute rendered =~ ~r/\d{4}-\d{2}-\d{2}/
      refute rendered =~ ~r/\d{2}:\d{2}:\d{2}/
      refute rendered =~ "generated at"
      refute rendered =~ ~r/\bms\b/
    end

    test "and no commit, branch or other VCS data" do
      rendered = Golden.render(spec())

      refute rendered =~ ~r/\b[0-9a-f]{40}\b/
      refute rendered =~ "commit"
      refute rendered =~ "branch"
    end
  end

  describe "cell notation" do
    test "each type renders to its documented form" do
      rendered =
        Golden.render(
          spec(%{
            columns: ["Item", "Cell"],
            rows: [
              %{"Item" => {:code, "a"}, "Cell" => {:code, "backticked"}},
              %{"Item" => {:code, "b"}, "Cell" => {:atom, :an_atom}},
              %{"Item" => {:code, "c"}, "Cell" => {:locus, "lib/x.ex", 7}},
              %{"Item" => {:code, "d"}, "Cell" => {:locus, "lib/y.ex", nil}},
              %{"Item" => {:code, "e"}, "Cell" => {:version, "a1b2c3d4"}},
              %{"Item" => {:code, "f"}, "Cell" => {:raw, "verbatim ·"}},
              %{"Item" => {:code, "g"}, "Cell" => :absent},
              %{"Item" => {:code, "h"}, "Cell" => nil},
              %{"Item" => {:code, "i"}, "Cell" => "plain"}
            ]
          })
        )

      assert rendered =~ "`backticked`"
      assert rendered =~ "`:an_atom`"
      assert rendered =~ "`lib/x.ex:7`"
      assert rendered =~ "`lib/y.ex`"
      assert rendered =~ "`a1b2c3d4`"
      assert rendered =~ "verbatim ·"
      assert rendered =~ "plain"
    end

    test "an absent value and a nil both render as the em-dash glyph" do
      rendered =
        Golden.render(
          spec(%{
            columns: ["Item", "Cell"],
            rows: [
              %{"Item" => {:code, "g"}, "Cell" => :absent},
              %{"Item" => {:code, "h"}, "Cell" => nil}
            ]
          })
        )

      [_header, g, h] =
        rendered |> String.split("\n") |> Enum.filter(&String.contains?(&1, "|")) |> Enum.take(-3)

      assert g =~ "—"
      assert h =~ "—"
    end

    test "a nil-file locus is absent rather than a path of nothing" do
      rendered =
        Golden.render(
          spec(%{
            columns: ["Item", "Locus"],
            rows: [%{"Item" => {:code, "a"}, "Locus" => {:locus, nil, nil}}]
          })
        )

      assert rendered =~ "—"
    end
  end

  describe "stats" do
    test "stat/2 keeps the counts as data and renders the same line" do
      stat = Golden.stat("2 items", [{"verified", 1}, {"nothing", 1}])

      assert stat.lead == "2 items"
      assert stat.dims == [{"verified", 1}, {"nothing", 1}]

      assert IO.iodata_to_binary(stat.text) ==
               IO.iodata_to_binary(Golden.stat_line(stat.lead, stat.dims))
    end

    test "the rendered line has the documented grammar" do
      line =
        "2 items" |> Golden.stat_line([{"verified", 1}, {"nothing", 1}]) |> IO.iodata_to_binary()

      assert line == "**2 items** · verified 1 · nothing 1"
    end

    test "a bare label is a flag, with no value after it" do
      line = "3 things" |> Golden.stat_line([{"ok", 2}, "clean"]) |> IO.iodata_to_binary()

      assert line == "**3 things** · ok 2 · clean"
    end

    test "and stats reach the output" do
      rendered = Golden.render(spec(%{stats: [Golden.stat("2 items", [{"verified", 1}])]}))

      assert rendered =~ "**2 items** · verified 1"
    end
  end

  describe "grouping" do
    test "groups render under their own headings, each with its own table" do
      rendered =
        Golden.render(
          spec(%{
            rows: nil,
            groups: [
              %{
                heading: "First",
                rows: [%{"Item" => {:code, "a"}, "Evidence" => :absent, "Locus" => :absent}]
              },
              %{
                heading: "Second",
                rows: [%{"Item" => {:code, "b"}, "Evidence" => :absent, "Locus" => :absent}]
              }
            ]
          })
        )

      assert rendered =~ "## First"
      assert rendered =~ "## Second"
      assert String.split(rendered, "| Item |") |> length() == 3
    end
  end
end
