defmodule Surfex.Golden do
  @moduledoc """
  The ONE renderer for a project's surface goldens.

  A **surface golden** is a document generated from a source scan, listing what the code
  declares, gated so that it cannot disagree with the code: CI regenerates it and
  byte-compares, and a difference fails the build. The document therefore cannot lie —
  which is the only property that makes a generated document worth reading three weeks
  later.

  Each scanner builds a plain data spec and hands it here. **The renderer IS the
  convention**: notation lives in one place, so per-file dialects cannot form — and, now
  that more than one project renders goldens, per-*project* dialects cannot either.

  ## The shape a golden always has

    1. **Header block** — line 1 `# <NAME>`; line 2 the one-line `:purpose`; line 3 the
       machine-parseable attribution `Generated by \`mix <task> --write\` · gate
       \`<gate>\` (HARD|ADVISORY) — do not edit; a drift FAILS the gate`. Domain
       `:prose` (semantics, class ladders) FOLLOWS the block, unconstrained.
    2. **Stats line(s)** — each `**<lead>** · <label> <n> · …` (see `stat_line/2`); every
       golden carries at least a row count.
    3. **Tables** — first column = the catalogued item (backticked); last column
       conventionally `Locus`. Cells are TYPED (`t:cell/0`) so the renderer — not each
       caller — owns the backtick/atom/locus/`—` notation. Optional grouping:
       `## <heading>` with per-group tables.

  **No timestamps or VCS data are ever emitted.** A golden is a stable function of source;
  a date makes it drift against itself on a quiet day, and a gate that cries wolf gets
  disabled. Dates belong in a report, never here. This is a lesson paid for once already in
  the project this came from, and it is the one rule most likely to be re-broken.

  ## What this does NOT know

  The **evidence ladder** — whether a thing is `model_checked`, `static_gate`, `property`,
  `unit_test` or NOTHING — is the calling project's vocabulary, and differs between them.
  So does what a surface *is*. This renders typed cells; it never interprets them.

  ## Determinism

  `render/1` is a pure function of its spec and is invariant under the input order of a row
  map's keys (cells are pulled in `:columns` order) and under the input order of the row
  list (rows are sorted by `:sort`, default the first column's natural key). So two specs
  that differ only in such orderings render identical bytes — **the property every drift
  gate rests on**, and the reason it is asserted in this package's tests rather than
  assumed.

  > Extracted from `agentronic`'s `Maatronic.SourceScan.Golden`, where ten goldens have
  > used it in production. Behaviour is unchanged; only the prose was rewritten for a home
  > that serves more than one project.
  """

  @typedoc """
  A typed table cell — the renderer formats it, so notation is central, not per-caller:

    * `{:code, io}` → `` `io` `` (the backticked-item rule)
    * `{:atom, a}` → `` `:a` `` (atoms always backticked, e.g. an effect class `:local`)
    * `{:locus, file, line}` → `` `file:line` `` (a `nil` file ⇒ `—`; a `nil` line drops the
      `:line`, so a hashed-locus surface passes `{:locus, file, nil}` for a bare-path Locus)
    * `{:version, hash}` → `` `hash` `` (a content version — `Surfex.SourceScan.definition_hash/1`'s
      8-hex output; a `nil` hash ⇒ `—`). Named rather than a bare `{:code, …}` so the
      content-version notation lives in one place across every golden's `Version` column.
    * `{:raw, io}` → verbatim (escape hatch for a composite cell like `` `unit_test` · tagged``)
    * `:absent` / `nil` → `—` (the absent-value glyph)
    * a plain binary → verbatim
  """
  @type cell ::
          {:code, iodata}
          | {:atom, atom}
          | {:locus, String.t() | nil, pos_integer | nil}
          | {:version, String.t() | nil}
          | {:raw, iodata}
          | :absent
          | nil
          | binary

  @typedoc "One table row: column-name => cell. Order-independent (cells pulled in `:columns` order)."
  @type row :: %{optional(String.t()) => cell}

  @typedoc """
  One stats line as DATA: the bold `:lead`, its `:dims` (`{label, value}` pairs / bare flags), and
  the rendered `:text`. Built by `stat/2` so the renderer AND any cross-surface report read the
  same counts — the report never parses the markdown.
  """
  @type stat :: %{lead: iodata, dims: [{iodata, term} | iodata], text: iodata}

  @typedoc """
  A `## <heading>` grouped table. `:columns` overrides the spec's top-level columns for this group —
  for a golden whose sub-tables have different shapes (e.g. AUTHZ's boundary ops vs runtime seams).
  """
  @type group :: %{:heading => iodata, :rows => [row], optional(:columns) => [String.t()]}

  @typedoc """
  A surface-golden spec. `:groups` and `:rows` are mutually exclusive — supply `:groups` for a
  grouped golden (`SPEC_COVERAGE`), `:rows` for a flat one. `:sort` is a row → sortable key (rows
  are sorted within each group); it defaults to the first column's natural key.
  """
  @type spec :: %{
          :name => String.t(),
          :purpose => iodata,
          :task => String.t(),
          :gate => String.t(),
          :hardness => :hard | :advisory,
          :columns => [String.t()],
          optional(:prose) => iodata,
          optional(:stats) => [stat],
          optional(:notes) => iodata,
          optional(:groups) => [group],
          optional(:rows) => [row],
          optional(:sort) => (row -> term)
        }

  @doc "Render `spec` to golden markdown. Pure; order-invariant per the moduledoc."
  @spec render(spec) :: String.t()
  def render(spec) do
    prefix =
      [header(spec), block(spec[:prose]), stats_block(spec[:stats]), block(spec[:notes])]
      |> Enum.reject(&blank?/1)
      |> Enum.intersperse("\n\n")

    IO.iodata_to_binary([prefix, "\n\n", tables(spec)])
  end

  @doc """
  A stats line as DATA (`t:stat/0`): `lead` + `dims` + the rendered `text`. Each golden
  passes these in `spec.stats`; a cross-surface report reads `lead`/`dims` from the same value, so the
  report's counts round-trip the golden's stats line by construction.
  """
  @spec stat(iodata, [{iodata, term} | iodata]) :: stat
  def stat(lead, dims), do: %{lead: lead, dims: dims, text: stat_line(lead, dims)}

  @doc """
  Build the stats line STRING: `**<lead>** · <label> <value> · …`. `lead` is the pre-bold
  summary (`"963 sections"`, or a label like `"Freshness (of tagged validations)"`); `dims` is a list
  of `{label, value}` (a bare `label` is a flag). Prefer `stat/2` in a spec so the counts stay data.
  """
  @spec stat_line(iodata, [{iodata, term} | iodata]) :: iodata
  def stat_line(lead, dims) do
    parts =
      Enum.map(dims, fn
        {label, value} -> [to_io(label), " ", to_io(value)]
        label -> to_io(label)
      end)

    ["**", lead, "**", Enum.map(parts, &[" · ", &1])]
  end

  # ── header ──────────────────────────────────────────────────────────

  # The header BLOCK is three contiguous lines — title, one-line purpose, attribution — so
  # a reader (or a parser) recovers name/purpose/task/gate/hardness from the first three lines.
  defp header(%{name: name, purpose: purpose} = spec) do
    ["# ", name, "\n", purpose, "\n", attribution(spec)]
  end

  defp attribution(%{task: task, gate: gate, hardness: hardness}) do
    [
      "Generated by `mix ",
      task,
      " --write` · gate `",
      gate,
      "` (",
      hardness(hardness),
      ") — do not edit; a drift FAILS the gate."
    ]
  end

  defp hardness(:hard), do: "HARD"
  defp hardness(:advisory), do: "ADVISORY"

  # ── stats ───────────────────────────────────────────────────────────

  defp stats_block(nil), do: []
  defp stats_block([]), do: []
  defp stats_block(stats), do: stats |> Enum.map(& &1.text) |> Enum.intersperse("\n\n")

  # ── tables ──────────────────────────────────────────────────────────

  defp tables(%{groups: groups} = spec) do
    Enum.map(groups, fn %{heading: heading, rows: rows} = group ->
      cols = Map.get(group, :columns) || spec.columns
      ["## ", heading, "\n\n", table(cols, sort_rows(rows, spec))]
    end)
  end

  defp tables(%{rows: rows} = spec) do
    table(spec.columns, sort_rows(rows, spec))
  end

  defp table(columns, rows) do
    [
      "| ",
      Enum.intersperse(columns, " | "),
      " |\n",
      "|",
      Enum.map(columns, fn _ -> "---|" end),
      "\n",
      Enum.map(rows, &row(columns, &1))
    ]
  end

  defp row(columns, row) do
    cells = Enum.map(columns, fn col -> cell(Map.get(row, col, :absent)) end)
    ["| ", Enum.intersperse(cells, " | "), " |\n"]
  end

  defp cell({:code, io}), do: ["`", io, "`"]
  defp cell({:atom, a}), do: ["`", inspect(a), "`"]
  defp cell({:locus, nil, _line}), do: "—"
  defp cell({:locus, file, nil}), do: ["`", file, "`"]
  defp cell({:locus, file, line}), do: ["`", file, ":", to_string(line), "`"]
  defp cell({:version, nil}), do: "—"
  defp cell({:version, hash}), do: ["`", hash, "`"]
  defp cell({:raw, io}), do: io
  defp cell(:absent), do: "—"
  defp cell(nil), do: "—"
  defp cell(bin) when is_binary(bin), do: bin

  # ── determinism helpers ─────────────────────────────────────────────

  defp sort_rows(rows, spec) do
    key = Map.get(spec, :sort) || fn r -> natural_key(first_cell_text(r, spec.columns)) end
    Enum.sort_by(rows, key)
  end

  defp first_cell_text(row, [first | _]), do: cell_text(Map.get(row, first, :absent))

  defp cell_text({:code, io}), do: IO.iodata_to_binary(io)
  defp cell_text({:atom, a}), do: inspect(a)
  defp cell_text({:raw, io}), do: IO.iodata_to_binary(io)
  defp cell_text(bin) when is_binary(bin), do: bin
  defp cell_text(_), do: ""

  @doc """
  A natural sort key for an identifier-ish string: alternating text / integer chunks, so `Foo.9`
  sorts before `Foo.10`. The renderer's default row order when a spec supplies no `:sort`.
  """
  @spec natural_key(String.t()) :: [String.t() | {0, integer}]
  def natural_key(text) do
    ~r/\d+|\D+/
    |> Regex.scan(text)
    |> Enum.map(fn [chunk] ->
      case Integer.parse(chunk) do
        {n, ""} -> {0, n}
        _ -> chunk
      end
    end)
  end

  # ── shared ──────────────────────────────────────────────────────────

  defp block(nil), do: []
  defp block(io), do: io

  defp blank?(nil), do: true
  defp blank?([]), do: true
  defp blank?(""), do: true
  defp blank?(_), do: false

  defp to_io(v) when is_integer(v), do: Integer.to_string(v)
  defp to_io(v), do: v
end
